# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('catalog', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='audio_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_messages', to='catalog.audiomessage'),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignrule',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignruletime',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='times', to='campaigns.campaignrule'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_campaign_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_targets', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_targets', to='organizations.resourcescope'),
        ),
    ]
