# Generated by Django 5.0.14 on 2026-09-07 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiocontent',
            name='rights_holder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='audiocontent',
            name='rights_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='audiocontent',
            name='rights_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiocontent',
            name='rights_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rights_verified_audio_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='audioasset',
            constraint=models.UniqueConstraint(condition=models.Q(('asset_role', 'ORIGINAL'), ('processing_status', 'READY')), fields=('checksum_sha256',), name='uniq_ready_audio_asset_checksum'),
        ),
    ]
