# Generated by Django 5.0.14 on 2026-07-30 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('GLOBAL', 'Global'), ('PRIVATE', 'Private'), ('SHARED', 'Shared')], default='GLOBAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('DISABLED', 'Disabled'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('cover_storage_key', models.CharField(blank=True, max_length=512)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPlaylist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('priority', models.IntegerField(default=0)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('order_mode', models.CharField(choices=[('SEQUENTIAL', 'Sequential'), ('SHUFFLE', 'Shuffle'), ('WEIGHTED', 'Weighted')], default='SHUFFLE', max_length=20)),
                ('repeat_song_gap_count', models.PositiveIntegerField(default=10)),
                ('max_same_genre_in_row', models.PositiveIntegerField(default=3)),
                ('avoid_same_tag_in_row', models.BooleanField(default=True)),
                ('crossfade_ms', models.PositiveIntegerField(default=0)),
                ('fade_in_ms', models.PositiveIntegerField(default=0)),
                ('fade_out_ms', models.PositiveIntegerField(default=0)),
                ('normalize_loudness', models.BooleanField(default=True)),
                ('target_lufs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('playlist_type', models.CharField(choices=[('MANUAL', 'Manual'), ('RULE_BASED', 'Rule based')], default='MANUAL', max_length=20)),
                ('visibility', models.CharField(choices=[('GLOBAL', 'Global'), ('PRIVATE', 'Private'), ('SHARED', 'Shared')], default='GLOBAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('DISABLED', 'Disabled'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField(default=1)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded')], default='CREATED', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSnapshotItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
