# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('organizations', '0002_initial'),
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='channelplaylist',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_playlists', to='playlists.channel'),
        ),
        migrations.AddField(
            model_name='channelpolicy',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='policy', to='playlists.channel'),
        ),
        migrations.AddField(
            model_name='contentaccessgrant',
            name='audio_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='catalog.audiocontent'),
        ),
        migrations.AddField(
            model_name='contentaccessgrant',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='playlists.channel'),
        ),
        migrations.AddField(
            model_name='contentaccessgrant',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_access_grants', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='contentaccessgrant',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_content_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='playlists', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='contentaccessgrant',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='channelplaylist',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_playlists', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_playlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlist_items', to='catalog.song'),
        ),
        migrations.AddField(
            model_name='playlistsnapshot',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='playlistsnapshot',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_playlist_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlistsnapshotitem',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='playlists.playlistsnapshot'),
        ),
        migrations.AddField(
            model_name='playlistsnapshotitem',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlist_snapshot_items', to='catalog.song'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(fields=('owner_company', 'code'), name='uniq_channel_owner_code'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_company__isnull', True)), fields=('code',), name='uniq_global_channel_code'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['owner_company', 'status'], name='playlists_p_owner_c_61e944_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['created_at'], name='playlists_p_created_20c807_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['updated_at'], name='playlists_p_updated_3778d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('owner_company', 'code'), name='uniq_playlist_owner_code'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_company__isnull', True)), fields=('code',), name='uniq_global_playlist_code'),
        ),
        migrations.AddConstraint(
            model_name='contentaccessgrant',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('audio_content__isnull', False), ('channel__isnull', True), ('playlist__isnull', True)), models.Q(('audio_content__isnull', True), ('channel__isnull', True), ('playlist__isnull', False)), models.Q(('audio_content__isnull', True), ('channel__isnull', False), ('playlist__isnull', True)), _connector='OR'), name='content_access_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='channelplaylist',
            constraint=models.UniqueConstraint(fields=('channel', 'playlist'), name='uniq_channel_playlist'),
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['playlist', 'position'], name='playlists_p_playlis_84fb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['created_at'], name='playlists_p_created_b02895_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['updated_at'], name='playlists_p_updated_adea76_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.UniqueConstraint(fields=('playlist', 'position'), name='uniq_playlist_item_position'),
        ),
        migrations.AddIndex(
            model_name='playlistsnapshot',
            index=models.Index(fields=['playlist', 'status'], name='playlists_p_playlis_8468bb_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistsnapshot',
            index=models.Index(fields=['created_at'], name='playlists_p_created_e806cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlistsnapshot',
            constraint=models.UniqueConstraint(fields=('playlist', 'version'), name='uniq_playlist_snapshot_version'),
        ),
        migrations.AddConstraint(
            model_name='playlistsnapshotitem',
            constraint=models.UniqueConstraint(fields=('snapshot', 'position'), name='uniq_playlist_snapshot_item_position'),
        ),
    ]
