# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('catalog', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_volume', models.PositiveSmallIntegerField(default=60)),
                ('minimum_volume', models.PositiveSmallIntegerField(default=0)),
                ('maximum_volume', models.PositiveSmallIntegerField(default=100)),
                ('allow_local_volume_change', models.BooleanField(default=True)),
                ('allow_channel_change', models.BooleanField(default=False)),
                ('allow_pause', models.BooleanField(default=False)),
                ('allow_skip', models.BooleanField(default=False)),
                ('allow_manual_message', models.BooleanField(default=False)),
                ('lock_schedule', models.BooleanField(default=False)),
                ('offline_cache_days', models.PositiveIntegerField(default=7)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PlaybackPolicyAllowedChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaybackPolicyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaybackSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=120)),
                ('close_reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('READY', 'Ready'), ('SUPERSEDED', 'Superseded'), ('ERROR', 'Error')], db_index=True, default='GENERATING', max_length=20)),
                ('generated_at', models.DateTimeField(db_index=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(max_length=128)),
                ('schedule_version', models.PositiveIntegerField(blank=True, null=True)),
                ('policy_version', models.PositiveIntegerField(blank=True, null=True)),
                ('total_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_manifests', to='organizations.company')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_manifests', to='organizations.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ContentManifestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('reason', models.CharField(choices=[('SCHEDULE', 'Schedule'), ('CHANNEL', 'Channel'), ('PLAYLIST', 'Playlist'), ('CAMPAIGN', 'Campaign'), ('FALLBACK', 'Fallback')], max_length=20)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('audio_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifest_items', to='catalog.audioasset')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='playback.contentmanifest')),
            ],
        ),
        migrations.CreateModel(
            name='PlaybackEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('planned_duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('played_duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('INTERRUPTED', 'Interrupted'), ('ERROR', 'Error')], max_length=20)),
                ('source', models.CharField(choices=[('SCHEDULE', 'Schedule'), ('MANUAL', 'Manual'), ('CAMPAIGN', 'Campaign'), ('FALLBACK', 'Fallback'), ('OFFLINE_RECOVERY', 'Offline recovery')], max_length=30)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('audio_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_events', to='catalog.audioasset')),
                ('audio_content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playback_events', to='catalog.audiocontent')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_events', to='campaigns.campaign')),
            ],
        ),
    ]
