# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('playback', '0001_initial'),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbackevent',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_events', to='playlists.channel'),
        ),
        migrations.AddField(
            model_name='playbackevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playback_events', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='playbackevent',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_events', to='playlists.playlist'),
        ),
    ]
