# Generated by Django 5.0.14 on 2026-09-04 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_zonechannelassignment_and_more'),
        ('playback', '0004_initial'),
        ('playlists', '0004_channelsnapshot_channelsnapshotplaylist_and_more'),
        ('scheduling', '0004_schedulesnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneOperationalSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('SUPERSEDED', 'Superseded'), ('ERROR', 'Error')], db_index=True, default='READY', max_length=20)),
                ('checksum', models.CharField(max_length=128)),
                ('generated_at', models.DateTimeField(db_index=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zone_operational_snapshots', to='playlists.channel')),
                ('channel_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zone_operational_snapshots', to='playlists.channelsnapshot')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_operational_snapshots', to='organizations.company')),
                ('schedule_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zone_operational_snapshots', to='scheduling.schedulesnapshot')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_snapshots', to='organizations.zone')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'status'], name='playback_zo_company_6d7e24_idx'), models.Index(fields=['zone', 'version'], name='playback_zo_zone_id_78744c_idx'), models.Index(fields=['created_at'], name='playback_zo_created_6dffd3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='zoneoperationalsnapshot',
            constraint=models.UniqueConstraint(fields=('zone', 'version'), name='uniq_zone_operational_snapshot_version'),
        ),
    ]
