# Generated by Django 5.0.14 on 2026-09-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playback', '0005_zoneoperationalsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmanifest',
            name='operational_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_manifests', to='playback.zoneoperationalsnapshot'),
        ),
    ]
