# Generated by Django 5.0.14 on 2026-09-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
