# Generated by Django 5.0.14 on 2026-09-04 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_schedule_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded')], db_index=True, default='CREATED', max_length=20)),
                ('timezone', models.CharField(max_length=64)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_schedule_snapshots', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='scheduling.schedule')),
            ],
            options={
                'indexes': [models.Index(fields=['schedule', 'status'], name='scheduling__schedul_053af0_idx'), models.Index(fields=['created_at'], name='scheduling__created_bcf9f6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='schedulesnapshot',
            constraint=models.UniqueConstraint(fields=('schedule', 'version'), name='uniq_schedule_snapshot_version'),
        ),
    ]
