# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyrolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_permissions', to='authorization.companyrole'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['permission_level', 'is_active'], name='authorizati_permiss_a8d09f_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['created_at'], name='authorizati_created_9b0c23_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['updated_at'], name='authorizati_updated_0eb3e0_idx'),
        ),
        migrations.AddField(
            model_name='companyrolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_role_permissions', to='authorization.permission'),
        ),
        migrations.AddIndex(
            model_name='platformrole',
            index=models.Index(fields=['is_active'], name='authorizati_is_acti_95d236_idx'),
        ),
        migrations.AddIndex(
            model_name='platformrole',
            index=models.Index(fields=['created_at'], name='authorizati_created_9b5473_idx'),
        ),
        migrations.AddIndex(
            model_name='platformrole',
            index=models.Index(fields=['updated_at'], name='authorizati_updated_54f286_idx'),
        ),
        migrations.AddField(
            model_name='platformrolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_role_permissions', to='authorization.permission'),
        ),
        migrations.AddField(
            model_name='platformrolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_permissions', to='authorization.platformrole'),
        ),
        migrations.AddField(
            model_name='userplatformrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_platform_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userplatformrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='authorization.platformrole'),
        ),
        migrations.AddField(
            model_name='userplatformrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='companyrole',
            index=models.Index(fields=['company', 'is_active'], name='authorizati_company_e51d67_idx'),
        ),
        migrations.AddIndex(
            model_name='companyrole',
            index=models.Index(fields=['created_at'], name='authorizati_created_19fbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='companyrole',
            index=models.Index(fields=['updated_at'], name='authorizati_updated_ac1d1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyrole',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_company_role_company_code'),
        ),
        migrations.AddConstraint(
            model_name='companyrole',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('code',), name='uniq_global_company_role_code'),
        ),
        migrations.AddConstraint(
            model_name='companyrolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uniq_company_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='platformrolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uniq_platform_role_permission'),
        ),
        migrations.AddIndex(
            model_name='userplatformrole',
            index=models.Index(fields=['user', 'revoked_at'], name='authorizati_user_id_37a98e_idx'),
        ),
        migrations.AddIndex(
            model_name='userplatformrole',
            index=models.Index(fields=['assigned_at'], name='authorizati_assigne_cffc13_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplatformrole',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'role'), name='uniq_active_user_platform_role'),
        ),
    ]
