# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_licenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenseassignment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_assignments', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='licenseassignment',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='billing.license'),
        ),
        migrations.AddField(
            model_name='licenseassignment',
            name='unassigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unassigned_licenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenseassignment',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_assignments', to='organizations.zone'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active', 'is_public'], name='billing_pla_is_acti_ad3f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['created_at'], name='billing_pla_created_8223a4_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['updated_at'], name='billing_pla_updated_e8b0ac_idx'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='license',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='billing.subscription'),
        ),
        migrations.AddIndex(
            model_name='licenseassignment',
            index=models.Index(fields=['company', 'assigned_at'], name='billing_lic_company_61f808_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseassignment',
            index=models.Index(fields=['zone', 'unassigned_at'], name='billing_lic_zone_id_205076_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseassignment',
            index=models.Index(fields=['created_at'], name='billing_lic_created_337ca4_idx'),
        ),
        migrations.AddConstraint(
            model_name='licenseassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('license',), name='uniq_active_assignment_per_license'),
        ),
        migrations.AddConstraint(
            model_name='licenseassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('zone',), name='uniq_active_license_per_zone'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['company', 'status'], name='billing_sub_company_dce5c4_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_period_end'], name='billing_sub_current_c59a21_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['created_at'], name='billing_sub_created_ef9656_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['updated_at'], name='billing_sub_updated_62c0fa_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['company', 'status'], name='billing_lic_company_dbfd17_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['created_at'], name='billing_lic_created_002b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['updated_at'], name='billing_lic_updated_aea89f_idx'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_license_company_code'),
        ),
    ]
