# Generated by Django 5.0.14 on 2026-07-30 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('entity_type', models.CharField(max_length=120)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('entity_label', models.CharField(blank=True, max_length=255)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
