# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content_type', models.CharField(choices=[('SONG', 'Song'), ('MESSAGE', 'Message')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('internal_code', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('GLOBAL', 'Global'), ('PRIVATE', 'Private'), ('SHARED', 'Shared')], default='GLOBAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('DISABLED', 'Disabled'), ('ERROR', 'Error'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('message_type', models.CharField(choices=[('CORPORATE', 'Corporate'), ('PROMOTION', 'Promotion'), ('INFORMATIONAL', 'Informational'), ('ALERT', 'Alert'), ('OTHER', 'Other')], max_length=20)),
                ('default_priority', models.IntegerField(default=0)),
                ('is_skippable', models.BooleanField(default=True)),
                ('internal_notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('job_type', models.CharField(choices=[('VALIDATE', 'Validate'), ('PROBE', 'Probe'), ('ANALYZE', 'Analyze'), ('NORMALIZE', 'Normalize'), ('TRANSCODE', 'Transcode'), ('GENERATE_PREVIEW', 'Generate preview'), ('CHECKSUM', 'Checksum')], max_length=30)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('queued_at', models.DateTimeField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('ai_generated', models.BooleanField(default=True)),
                ('generation_provider', models.CharField(blank=True, max_length=120)),
                ('generation_model', models.CharField(blank=True, max_length=120)),
                ('generation_reference', models.CharField(blank=True, max_length=255)),
                ('is_explicit', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='MANUAL', max_length=20)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=512)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('target_content_type', models.CharField(choices=[('SONG', 'Song'), ('MESSAGE', 'Message')], max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled')], db_index=True, default='CREATED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('asset_role', models.CharField(choices=[('ORIGINAL', 'Original'), ('NORMALIZED', 'Normalized'), ('STREAM', 'Stream'), ('OFFLINE', 'Offline'), ('PREVIEW', 'Preview')], max_length=20)),
                ('storage_backend', models.CharField(max_length=80)),
                ('storage_key', models.CharField(max_length=512)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('container_format', models.CharField(max_length=50)),
                ('codec', models.CharField(max_length=50)),
                ('bitrate_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('sample_rate_hz', models.PositiveIntegerField(blank=True, null=True)),
                ('channels', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('processing_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error'), ('ARCHIVED', 'Archived')], default='UPLOADED', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_from_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_assets', to='catalog.audioasset')),
            ],
        ),
        migrations.CreateModel(
            name='AudioAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('integrated_lufs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('true_peak_db', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('loudness_range', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('peak_db', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('silence_start_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('silence_end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('detected_bpm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('detected_key', models.CharField(blank=True, max_length=20)),
                ('analysis_version', models.CharField(max_length=80)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('audio_asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='analysis', to='catalog.audioasset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
