# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiocontent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audio_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiocontent',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audio_contents', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='audioasset',
            name='audio_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='catalog.audiocontent'),
        ),
        migrations.AddField(
            model_name='audiomessage',
            name='audio_content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='audio_message', to='catalog.audiocontent'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['is_active', 'sort_order'], name='catalog_gen_is_acti_4246bd_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['created_at'], name='catalog_gen_created_504cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['updated_at'], name='catalog_gen_updated_521186_idx'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='audio_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_jobs', to='catalog.audioasset'),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='song', to='catalog.audiocontent'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='songtag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_song_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songtag',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='song_tags', to='catalog.song'),
        ),
        migrations.AddField(
            model_name='songtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='song_tags', to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='catalog.tagcategory'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='created_audio_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to='catalog.audiocontent'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='audiocontent',
            index=models.Index(fields=['owner_company', 'status'], name='catalog_aud_owner_c_e7ebd7_idx'),
        ),
        migrations.AddIndex(
            model_name='audiocontent',
            index=models.Index(fields=['content_type', 'status'], name='catalog_aud_content_af9be0_idx'),
        ),
        migrations.AddIndex(
            model_name='audiocontent',
            index=models.Index(fields=['created_at'], name='catalog_aud_created_0eb0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='audiocontent',
            index=models.Index(fields=['updated_at'], name='catalog_aud_updated_31ac5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiocontent',
            constraint=models.UniqueConstraint(fields=('owner_company', 'internal_code'), name='uniq_owner_audio_internal_code'),
        ),
        migrations.AddConstraint(
            model_name='audiocontent',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_company__isnull', True)), fields=('internal_code',), name='uniq_global_audio_internal_code'),
        ),
        migrations.AddIndex(
            model_name='audioasset',
            index=models.Index(fields=['audio_content', 'processing_status'], name='catalog_aud_audio_c_9688df_idx'),
        ),
        migrations.AddIndex(
            model_name='audioasset',
            index=models.Index(fields=['created_at'], name='catalog_aud_created_be2a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='audioasset',
            index=models.Index(fields=['updated_at'], name='catalog_aud_updated_7da757_idx'),
        ),
        migrations.AddConstraint(
            model_name='audioasset',
            constraint=models.UniqueConstraint(fields=('audio_content', 'version', 'asset_role'), name='uniq_audio_asset_content_version_role'),
        ),
        migrations.AddConstraint(
            model_name='audioasset',
            constraint=models.UniqueConstraint(fields=('storage_backend', 'storage_key'), name='uniq_audio_asset_storage_key'),
        ),
        migrations.AddConstraint(
            model_name='audioasset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('processing_status', 'READY')), fields=('audio_content',), name='uniq_primary_ready_asset_per_content'),
        ),
        migrations.AddConstraint(
            model_name='songtag',
            constraint=models.UniqueConstraint(fields=('song', 'tag'), name='uniq_song_tag'),
        ),
        migrations.AddConstraint(
            model_name='songtag',
            constraint=models.CheckConstraint(check=models.Q(('source', 'AUTOMATIC'), ('confidence__isnull', True), _connector='OR'), name='song_tag_confidence_when_auto'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['category', 'is_active'], name='catalog_tag_categor_9c09d6_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['created_at'], name='catalog_tag_created_bd58b1_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['updated_at'], name='catalog_tag_updated_812d4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='uniq_tag_category_slug'),
        ),
    ]
