# Generated by Django 5.0.14 on 2026-07-30 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='AVAILABLE', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(db_index=True)),
                ('unassigned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('billing_interval', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('included_licenses', models.PositiveIntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, max_length=20)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField(db_index=True)),
                ('renews_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('license_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('billing_provider', models.CharField(blank=True, max_length=80)),
                ('provider_customer_id', models.CharField(blank=True, max_length=255)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255)),
                ('commercial_terms', models.JSONField(blank=True, default=dict)),
                ('plan_snapshot', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
