# Generated by Django 5.0.14 on 2026-08-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
        ('organizations', '0003_companymembership_uniq_company_membership_single_company_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['trial_ends_at'], name='billing_sub_trial_e_074bc8_idx'),
        ),
    ]
