# Generated by Django 5.0.14 on 2026-07-30 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('hardware_id', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('DEDICATED_PLAYER', 'Dedicated player'), ('DESKTOP_APP', 'Desktop app'), ('MOBILE_APP', 'Mobile app'), ('OTHER', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance'), ('DISABLED', 'Disabled'), ('REVOKED', 'Revoked')], db_index=True, default='PROVISIONING', max_length=30)),
                ('os_name', models.CharField(blank=True, max_length=120)),
                ('os_version', models.CharField(blank=True, max_length=120)),
                ('app_version', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=32)),
                ('storage_total_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('storage_free_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCachedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DOWNLOADED', 'Downloaded'), ('VERIFIED', 'Verified'), ('CORRUPTED', 'Corrupted'), ('DELETED', 'Deleted')], default='PENDING', max_length=20)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('checksum_valid', models.BooleanField(default=False)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('SET_VOLUME', 'Set volume'), ('CHANGE_CHANNEL', 'Change channel'), ('PAUSE', 'Pause'), ('RESUME', 'Resume'), ('SKIP', 'Skip'), ('SYNC', 'Sync'), ('RESTART', 'Restart'), ('UPDATE_APP', 'Update app'), ('REFRESH_CONFIGURATION', 'Refresh configuration')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('ACKNOWLEDGED', 'Acknowledged'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.CharField(max_length=255, unique=True)),
                ('secret_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('app_version', models.CharField(blank=True, max_length=120)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('playback_status', models.CharField(choices=[('STOPPED', 'Stopped'), ('PLAYING', 'Playing'), ('PAUSED', 'Paused'), ('BUFFERING', 'Buffering'), ('ERROR', 'Error')], default='STOPPED', max_length=20)),
                ('position_ms', models.PositiveBigIntegerField(default=0)),
                ('volume', models.PositiveSmallIntegerField(default=60)),
                ('is_online', models.BooleanField(default=False)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('manifest_version', models.PositiveIntegerField(blank=True, null=True)),
                ('schedule_version', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DOWNLOADING', 'Downloading'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('bytes_total', models.PositiveBigIntegerField(default=0)),
                ('bytes_downloaded', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceZoneAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_role', models.CharField(choices=[('PRIMARY', 'Primary'), ('STANDBY', 'Standby')], default='PRIMARY', max_length=20)),
                ('assigned_at', models.DateTimeField(db_index=True)),
                ('unassigned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
