# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('devices', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='devicecachedasset',
            name='audio_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_caches', to='catalog.audioasset'),
        ),
        migrations.AddField(
            model_name='devicecachedasset',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cached_assets', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_commands', to='organizations.company'),
        ),
    ]
