# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0003_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companymembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_company_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipgrant',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_membership_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipgrant',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='organizations.companymembership'),
        ),
        migrations.AddField(
            model_name='membershipgrant',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_grants', to='authorization.companyrole'),
        ),
        migrations.AddField(
            model_name='membershippermissionoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permission_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershippermissionoverride',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_overrides', to='organizations.companymembership'),
        ),
        migrations.AddField(
            model_name='membershippermissionoverride',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_overrides', to='authorization.permission'),
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizational_units', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organizations.organizationalunit'),
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_groups', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='resourcegroupsite',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_members', to='organizations.resourcegroup'),
        ),
        migrations.AddField(
            model_name='resourcegroupzone',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_members', to='organizations.resourcegroup'),
        ),
        migrations.AddField(
            model_name='resourcescope',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_scopes', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='resourcescope',
            name='organizational_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_scopes', to='organizations.organizationalunit'),
        ),
        migrations.AddField(
            model_name='resourcescope',
            name='resource_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_scopes', to='organizations.resourcegroup'),
        ),
        migrations.AddField(
            model_name='membershippermissionoverride',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_overrides', to='organizations.resourcescope'),
        ),
        migrations.AddField(
            model_name='membershipgrant',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_grants', to='organizations.resourcescope'),
        ),
        migrations.AddField(
            model_name='site',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='site',
            name='organizational_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='organizations.organizationalunit'),
        ),
        migrations.AddField(
            model_name='resourcescope',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_scopes', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='resourcegroupsite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_group_memberships', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='zone',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='zone',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='resourcescope',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_scopes', to='organizations.zone'),
        ),
        migrations.AddField(
            model_name='resourcegroupzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_group_memberships', to='organizations.zone'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['company', 'status'], name='organizatio_company_b059e7_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['user', 'status'], name='organizatio_user_id_c718ec_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['created_at'], name='organizatio_created_1349cc_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['updated_at'], name='organizatio_updated_d3660e_idx'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uniq_company_membership_user'),
        ),
        migrations.AddIndex(
            model_name='organizationalunit',
            index=models.Index(fields=['company', 'unit_type'], name='organizatio_company_ad3238_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalunit',
            index=models.Index(fields=['company', 'is_active'], name='organizatio_company_f8ddea_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalunit',
            index=models.Index(fields=['created_at'], name='organizatio_created_ebf1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationalunit',
            index=models.Index(fields=['updated_at'], name='organizatio_updated_c07ff0_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationalunit',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_org_unit_company_code'),
        ),
        migrations.AddIndex(
            model_name='resourcegroup',
            index=models.Index(fields=['company', 'group_type', 'is_active'], name='organizatio_company_57333a_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcegroup',
            index=models.Index(fields=['created_at'], name='organizatio_created_430cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcegroup',
            index=models.Index(fields=['updated_at'], name='organizatio_updated_0db225_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourcegroup',
            constraint=models.UniqueConstraint(fields=('company', 'group_type', 'name'), name='uniq_resource_group_company_type_name'),
        ),
        migrations.AddIndex(
            model_name='membershippermissionoverride',
            index=models.Index(fields=['membership', 'effect'], name='organizatio_members_bf17c7_idx'),
        ),
        migrations.AddIndex(
            model_name='membershippermissionoverride',
            index=models.Index(fields=['scope'], name='organizatio_scope_i_b29fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='membershippermissionoverride',
            index=models.Index(fields=['created_at'], name='organizatio_created_6bf1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='membershippermissionoverride',
            index=models.Index(fields=['updated_at'], name='organizatio_updated_038d40_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipgrant',
            index=models.Index(fields=['membership', 'is_active'], name='organizatio_members_553dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipgrant',
            index=models.Index(fields=['scope', 'is_active'], name='organizatio_scope_i_dbd962_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipgrant',
            index=models.Index(fields=['created_at'], name='organizatio_created_75179a_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipgrant',
            index=models.Index(fields=['updated_at'], name='organizatio_updated_8c5a35_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['company', 'status'], name='organizatio_company_7dae27_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['created_at'], name='organizatio_created_8eb9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['updated_at'], name='organizatio_updated_d49b10_idx'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_site_company_code'),
        ),
        migrations.AddConstraint(
            model_name='resourcegroupsite',
            constraint=models.UniqueConstraint(fields=('group', 'site'), name='uniq_resource_group_site'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['company', 'status'], name='organizatio_company_409bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['site', 'status'], name='organizatio_site_id_d9860b_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['created_at'], name='organizatio_created_140897_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['updated_at'], name='organizatio_updated_fed983_idx'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='uniq_zone_site_code'),
        ),
        migrations.AddIndex(
            model_name='resourcescope',
            index=models.Index(fields=['company', 'scope_type'], name='organizatio_company_417887_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcescope',
            index=models.Index(fields=['created_at'], name='organizatio_created_7769c6_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcescope',
            index=models.Index(fields=['updated_at'], name='organizatio_updated_9bd0e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourcescope',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('organizational_unit__isnull', True), ('resource_group__isnull', True), ('scope_type', 'COMPANY'), ('site__isnull', True), ('zone__isnull', True)), models.Q(('organizational_unit__isnull', False), ('resource_group__isnull', True), ('scope_type', 'ORGANIZATIONAL_UNIT'), ('site__isnull', True), ('zone__isnull', True)), models.Q(('organizational_unit__isnull', True), ('resource_group__isnull', True), ('scope_type', 'SITE'), ('site__isnull', False), ('zone__isnull', True)), models.Q(('organizational_unit__isnull', True), ('resource_group__isnull', True), ('scope_type', 'ZONE'), ('site__isnull', True), ('zone__isnull', False)), models.Q(('organizational_unit__isnull', True), ('resource_group__isnull', False), ('scope_type', 'RESOURCE_GROUP'), ('site__isnull', True), ('zone__isnull', True)), _connector='OR'), name='resource_scope_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='resourcescope',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'COMPANY')), fields=('company',), name='uniq_company_scope'),
        ),
        migrations.AddConstraint(
            model_name='resourcescope',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'ORGANIZATIONAL_UNIT')), fields=('organizational_unit',), name='uniq_org_unit_scope'),
        ),
        migrations.AddConstraint(
            model_name='resourcescope',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'SITE')), fields=('site',), name='uniq_site_scope'),
        ),
        migrations.AddConstraint(
            model_name='resourcescope',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'ZONE')), fields=('zone',), name='uniq_zone_scope'),
        ),
        migrations.AddConstraint(
            model_name='resourcescope',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'RESOURCE_GROUP')), fields=('resource_group',), name='uniq_resource_group_scope'),
        ),
        migrations.AddConstraint(
            model_name='resourcegroupzone',
            constraint=models.UniqueConstraint(fields=('group', 'zone'), name='uniq_resource_group_zone'),
        ),
    ]
