# Generated by Django 5.0.14 on 2026-08-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_companymembership_uniq_company_membership_single_company_per_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('tax_id',), name='uniq_company_tax_id'),
        ),
    ]
