# Generated by Django 5.0.14 on 2026-09-04 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_companyinvitation'),
        ('playlists', '0003_playlist_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneChannelAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(db_index=True)),
                ('unassigned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_zone_channels', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_assignments', to='playlists.channel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_channel_assignments', to='organizations.company')),
                ('unassigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unassigned_zone_channels', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_assignments', to='organizations.zone')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'assigned_at'], name='organizatio_company_55f723_idx'), models.Index(fields=['channel', 'unassigned_at'], name='organizatio_channel_5f74c3_idx'), models.Index(fields=['zone', 'unassigned_at'], name='organizatio_zone_id_83fa49_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='zonechannelassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('zone',), name='uniq_active_channel_assignment_per_zone'),
        ),
    ]
