# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0003_initial'),
        ('organizations', '0002_initial'),
        ('playback', '0003_initial'),
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playbackpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_playback_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playbackpolicy',
            name='fallback_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_for_policies', to='playlists.channel'),
        ),
        migrations.AddField(
            model_name='playbackpolicyallowedchannel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowed_in_policies', to='playlists.channel'),
        ),
        migrations.AddField(
            model_name='playbackpolicyallowedchannel',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowed_channels', to='playback.playbackpolicy'),
        ),
        migrations.AddField(
            model_name='playbackpolicyassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_playback_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playbackpolicyassignment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playback_policy_assignments', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='playbackpolicyassignment',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='playback.playbackpolicy'),
        ),
        migrations.AddField(
            model_name='playbackpolicyassignment',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playback_policy_assignments', to='organizations.resourcescope'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playback_sessions', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playback_sessions', to='devices.device'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='manifest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_sessions', to='playback.contentmanifest'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playback_sessions', to='organizations.zone'),
        ),
        migrations.AddField(
            model_name='playbackevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='playback.playbacksession'),
        ),
        migrations.AddIndex(
            model_name='contentmanifest',
            index=models.Index(fields=['company', 'status'], name='playback_co_company_04235c_idx'),
        ),
        migrations.AddIndex(
            model_name='contentmanifest',
            index=models.Index(fields=['zone', 'version'], name='playback_co_zone_id_345ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='contentmanifest',
            index=models.Index(fields=['created_at'], name='playback_co_created_f968ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentmanifest',
            constraint=models.UniqueConstraint(fields=('zone', 'version'), name='uniq_manifest_zone_version'),
        ),
        migrations.AddConstraint(
            model_name='contentmanifestitem',
            constraint=models.UniqueConstraint(fields=('manifest', 'audio_asset'), name='uniq_manifest_audio_asset'),
        ),
        migrations.AddIndex(
            model_name='playbackpolicy',
            index=models.Index(fields=['company'], name='playback_pl_company_d47a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='playbackpolicy',
            index=models.Index(fields=['created_at'], name='playback_pl_created_ca6b82_idx'),
        ),
        migrations.AddIndex(
            model_name='playbackpolicy',
            index=models.Index(fields=['updated_at'], name='playback_pl_updated_3b9833_idx'),
        ),
        migrations.AddConstraint(
            model_name='playbackpolicy',
            constraint=models.CheckConstraint(check=models.Q(('maximum_volume__lte', 100), ('minimum_volume__gte', 0)), name='playback_policy_volume_range'),
        ),
        migrations.AddConstraint(
            model_name='playbackpolicyallowedchannel',
            constraint=models.UniqueConstraint(fields=('policy', 'channel'), name='uniq_policy_allowed_channel'),
        ),
        migrations.AddIndex(
            model_name='playbacksession',
            index=models.Index(fields=['company', 'started_at'], name='playback_pl_company_caaece_idx'),
        ),
        migrations.AddIndex(
            model_name='playbacksession',
            index=models.Index(fields=['zone', 'started_at'], name='playback_pl_zone_id_42602e_idx'),
        ),
        migrations.AddIndex(
            model_name='playbackevent',
            index=models.Index(fields=['company', 'started_at'], name='playback_pl_company_e9d71b_idx'),
        ),
        migrations.AddIndex(
            model_name='playbackevent',
            index=models.Index(fields=['session', 'started_at'], name='playback_pl_session_9fde1e_idx'),
        ),
        migrations.AddIndex(
            model_name='playbackevent',
            index=models.Index(fields=['audio_content', 'started_at'], name='playback_pl_audio_c_a035f9_idx'),
        ),
        migrations.AddIndex(
            model_name='playbackevent',
            index=models.Index(fields=['campaign', 'started_at'], name='playback_pl_campaig_b0b420_idx'),
        ),
    ]
