# Generated by Django 5.0.14 on 2026-09-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
