# Generated by Django 5.0.14 on 2026-09-04 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlist_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded')], db_index=True, default='CREATED', max_length=20)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelSnapshotPlaylist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('priority', models.IntegerField(default=0)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='current_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['owner_company', 'status'], name='playlists_c_owner_c_a2a1ab_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['created_at'], name='playlists_c_created_0c92af_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['updated_at'], name='playlists_c_updated_0d0cfc_idx'),
        ),
        migrations.AddField(
            model_name='channelsnapshot',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='playlists.channel'),
        ),
        migrations.AddField(
            model_name='channelsnapshot',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_channel_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelsnapshotplaylist',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_snapshot_references', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='channelsnapshotplaylist',
            name='playlist_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_snapshot_references', to='playlists.playlistsnapshot'),
        ),
        migrations.AddField(
            model_name='channelsnapshotplaylist',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlists', to='playlists.channelsnapshot'),
        ),
        migrations.AddIndex(
            model_name='channelsnapshot',
            index=models.Index(fields=['channel', 'status'], name='playlists_c_channel_15bec8_idx'),
        ),
        migrations.AddIndex(
            model_name='channelsnapshot',
            index=models.Index(fields=['created_at'], name='playlists_c_created_a6cf56_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelsnapshot',
            constraint=models.UniqueConstraint(fields=('channel', 'version'), name='uniq_channel_snapshot_version'),
        ),
        migrations.AddConstraint(
            model_name='channelsnapshotplaylist',
            constraint=models.UniqueConstraint(fields=('snapshot', 'playlist'), name='uniq_channel_snapshot_playlist'),
        ),
    ]
