# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('devices', '0002_initial'),
        ('organizations', '0001_initial'),
        ('playback', '0003_initial'),
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecommand',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_device_commands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicecredential',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicecredential',
            name='rotated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_to', to='devices.devicecredential'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_events', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='current_audio_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_states', to='catalog.audiocontent'),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='current_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_states', to='playlists.channel'),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='current_playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_states', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='state', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_states', to='organizations.zone'),
        ),
        migrations.AddField(
            model_name='devicesync',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_syncs', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='devicesync',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syncs', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicesync',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_syncs', to='playback.contentmanifest'),
        ),
        migrations.AddField(
            model_name='devicezoneassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicezoneassignment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_zone_assignments', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='devicezoneassignment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_assignments', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicezoneassignment',
            name='unassigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unassigned_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicezoneassignment',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_assignments', to='organizations.zone'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'status'], name='devices_dev_company_c2b2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_seen_at'], name='devices_dev_last_se_c75af6_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['created_at'], name='devices_dev_created_f36e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['updated_at'], name='devices_dev_updated_ea92d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_device_company_code'),
        ),
        migrations.AddConstraint(
            model_name='devicecachedasset',
            constraint=models.UniqueConstraint(fields=('device', 'audio_asset'), name='uniq_device_cached_asset'),
        ),
        migrations.AddIndex(
            model_name='devicezoneassignment',
            index=models.Index(fields=['company', 'assigned_at'], name='devices_dev_company_eff33e_idx'),
        ),
        migrations.AddIndex(
            model_name='devicezoneassignment',
            index=models.Index(fields=['zone', 'unassigned_at'], name='devices_dev_zone_id_9d5b47_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicezoneassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('unassigned_at__isnull', True)), fields=('device',), name='uniq_active_assignment_per_device'),
        ),
        migrations.AddConstraint(
            model_name='devicezoneassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment_role', 'PRIMARY'), ('unassigned_at__isnull', True)), fields=('zone',), name='uniq_active_primary_device_per_zone'),
        ),
    ]
