# Generated by Django 5.0.14 on 2026-09-07 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_initial'),
        ('organizations', '0007_zonechannelassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='devicezoneassignment',
            name='uniq_active_primary_device_per_zone',
        ),
        migrations.AddField(
            model_name='device',
            name='activation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVATED', 'Activated'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='administrative_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='device',
            name='configuration_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='device',
            name='connectivity_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('ONLINE', 'Online'), ('OFFLINE', 'Offline')], db_index=True, default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='organizations.zone'),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='idempotency_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'administrative_status'], name='devices_dev_company_ad79ef_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['company', 'activation_status'], name='devices_dev_company_ef35e6_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['zone', 'administrative_status'], name='devices_dev_zone_id_1cb43e_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'status'], name='devices_dev_device__0a9c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['company', 'created_at'], name='devices_dev_company_d48273_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecredential',
            index=models.Index(fields=['device', 'status'], name='devices_dev_device__dd1ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecredential',
            index=models.Index(fields=['expires_at'], name='devices_dev_expires_bc1dde_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicecommand',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('company', 'idempotency_key'), name='uniq_device_command_idempotency_key'),
        ),
        migrations.AddField(
            model_name='deviceactivation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_device_activations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceactivation',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activation_codes', to='devices.device'),
        ),
        migrations.AddIndex(
            model_name='deviceactivation',
            index=models.Index(fields=['device', 'expires_at'], name='devices_dev_device__1de094_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceactivation',
            index=models.Index(fields=['created_at'], name='devices_dev_created_862272_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceactivation',
            constraint=models.UniqueConstraint(condition=models.Q(('consumed_at__isnull', True), ('revoked_at__isnull', True)), fields=('device',), name='uniq_active_device_activation_per_device'),
        ),
    ]
