# Generated by Django 5.0.14 on 2026-09-07 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_audiocontent_rights_holder_and_more'),
        ('devices', '0005_backfill_device_zone'),
        ('organizations', '0007_zonechannelassignment_and_more'),
        ('playback', '0006_contentmanifest_operational_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceevent',
            name='audio_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_events', to='catalog.audioasset'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='configuration_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='external_event_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='manifest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_events', to='playback.contentmanifest'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='position_ms',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='received_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='sequence',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='last_sequence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('SET_VOLUME', 'Set volume'), ('MUTE', 'Mute'), ('UNMUTE', 'Unmute'), ('RESTART_PLAYBACK', 'Restart playback'), ('FORCE_SYNC', 'Force sync'), ('ENABLE', 'Enable'), ('DISABLE', 'Disable'), ('CHANGE_CHANNEL', 'Change channel'), ('PAUSE', 'Pause'), ('RESUME', 'Resume'), ('SKIP', 'Skip'), ('SYNC', 'Sync'), ('RESTART', 'Restart'), ('UPDATE_APP', 'Update app'), ('REFRESH_CONFIGURATION', 'Refresh configuration')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device', 'sequence'], name='devices_dev_device__5984f4_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['company', 'occurred_at'], name='devices_dev_company_39719f_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id__isnull', False)), fields=('device', 'external_event_id'), name='uniq_device_external_event'),
        ),
    ]
