OFFICIAL_PERMISSIONS = [
    {"code": "platform.companies.manage", "name": "Empresas", "module": "platform", "level": "PLATFORM"},
    {"code": "platform.content.manage", "name": "Contenido", "module": "platform", "level": "PLATFORM"},
    {"code": "platform.billing.manage", "name": "Facturacion", "module": "platform", "level": "PLATFORM"},
    {"code": "platform.support.manage", "name": "Soporte", "module": "platform", "level": "PLATFORM"},
    {"code": "company.settings.view", "name": "Ver ajustes", "module": "company", "level": "COMPANY"},
    {"code": "company.settings.manage", "name": "Gestionar ajustes", "module": "company", "level": "COMPANY"},
    {"code": "company.members.view", "name": "Ver miembros", "module": "company", "level": "COMPANY"},
    {"code": "company.members.manage", "name": "Gestionar miembros", "module": "company", "level": "COMPANY"},
    {"code": "catalog.view", "name": "Ver catalogo", "module": "catalog", "level": "COMPANY"},
    {"code": "playlists.view", "name": "Ver playlists", "module": "playlists", "level": "COMPANY"},
    {"code": "playlists.manage", "name": "Gestionar playlists", "module": "playlists", "level": "COMPANY"},
    {"code": "sites.view", "name": "Ver sedes", "module": "sites", "level": "COMPANY"},
    {"code": "sites.manage", "name": "Gestionar sedes", "module": "sites", "level": "COMPANY"},
    {"code": "zones.view", "name": "Ver zonas", "module": "zones", "level": "COMPANY"},
    {"code": "zones.manage", "name": "Gestionar zonas", "module": "zones", "level": "COMPANY"},
    {"code": "licenses.view", "name": "Ver licencias", "module": "licenses", "level": "COMPANY"},
    {"code": "licenses.assign", "name": "Asignar licencias", "module": "licenses", "level": "COMPANY"},
    {"code": "channels.view", "name": "Ver canales", "module": "channels", "level": "COMPANY"},
    {"code": "channels.select", "name": "Seleccionar canales", "module": "channels", "level": "COMPANY"},
    {"code": "channels.manage", "name": "Gestionar canales", "module": "channels", "level": "COMPANY"},
    {"code": "playback.view", "name": "Ver reproduccion", "module": "playback", "level": "COMPANY"},
    {"code": "playback.control", "name": "Controlar reproduccion", "module": "playback", "level": "COMPANY"},
    {"code": "playback.volume", "name": "Modificar volumen", "module": "playback", "level": "COMPANY"},
    {"code": "schedules.view", "name": "Ver programaciones", "module": "schedules", "level": "COMPANY"},
    {"code": "schedules.manage", "name": "Gestionar programaciones", "module": "schedules", "level": "COMPANY"},
    {"code": "campaigns.view", "name": "Ver campanas", "module": "campaigns", "level": "COMPANY"},
    {"code": "campaigns.manage", "name": "Gestionar campanas", "module": "campaigns", "level": "COMPANY"},
    {"code": "devices.view", "name": "Ver dispositivos", "module": "devices", "level": "COMPANY"},
    {"code": "devices.manage", "name": "Gestionar dispositivos", "module": "devices", "level": "COMPANY"},
    {"code": "audit.view", "name": "Ver auditoria", "module": "audit", "level": "COMPANY"},
    {"code": "billing.view", "name": "Ver facturacion", "module": "billing", "level": "COMPANY"},
    {"code": "billing.manage", "name": "Gestionar facturacion", "module": "billing", "level": "COMPANY"},
]

PLATFORM_ROLE_DEFINITIONS = {
    "SUPERADMIN": {
        "name": "Superadmin",
        "permissions": [
            "platform.companies.manage",
            "platform.content.manage",
            "platform.billing.manage",
            "platform.support.manage",
        ],
    },
    "INTERNAL_ADMIN": {
        "name": "Internal Admin",
        "permissions": [
            "platform.companies.manage",
            "platform.content.manage",
            "platform.billing.manage",
            "platform.support.manage",
        ],
    },
    "CONTENT_MANAGER": {"name": "Content Manager", "permissions": ["platform.content.manage"]},
    "SUPPORT_AGENT": {"name": "Support Agent", "permissions": ["platform.support.manage"]},
    "BILLING_MANAGER": {"name": "Billing Manager", "permissions": ["platform.billing.manage"]},
    "INTERNAL_READ_ONLY": {"name": "Internal Read Only", "permissions": []},
}

COMPANY_ROLE_DEFINITIONS = {
    "OWNER": {
        "name": "Owner",
        "description": "Control completo de la cuenta empresarial.",
        "permissions": [
            "company.settings.view",
            "company.settings.manage",
            "company.members.view",
            "company.members.manage",
            "catalog.view",
            "playlists.view",
            "playlists.manage",
            "sites.view",
            "sites.manage",
            "zones.view",
            "zones.manage",
            "licenses.view",
            "licenses.assign",
            "channels.view",
            "channels.select",
            "channels.manage",
            "playback.view",
            "playback.control",
            "playback.volume",
            "schedules.view",
            "schedules.manage",
            "campaigns.view",
            "campaigns.manage",
            "devices.view",
            "devices.manage",
            "audit.view",
            "billing.view",
            "billing.manage",
        ],
    },
    "MANAGER": {
        "name": "Manager",
        "description": "Gestion operativa de empresa, sedes, zonas, canales y dispositivos.",
        "permissions": [
            "company.settings.view",
            "company.settings.manage",
            "company.members.view",
            "catalog.view",
            "playlists.view",
            "sites.view",
            "sites.manage",
            "zones.view",
            "zones.manage",
            "licenses.view",
            "channels.view",
            "channels.select",
            "channels.manage",
            "playback.view",
            "playback.control",
            "playback.volume",
            "schedules.view",
            "campaigns.view",
            "devices.view",
            "devices.manage",
            "audit.view",
        ],
    },
    "EDITOR_PLAYLISTS": {
        "name": "Editor Playlists",
        "description": "Gestion de catalogo consultable, playlists y programaciones.",
        "permissions": [
            "catalog.view",
            "playlists.view",
            "playlists.manage",
            "channels.view",
            "schedules.view",
            "schedules.manage",
        ],
    },
    "OPERADOR_SEDES": {
        "name": "Operador Sedes",
        "description": "Operacion diaria de sedes y zonas asignadas.",
        "permissions": [
            "sites.view",
            "zones.view",
            "channels.view",
            "channels.select",
            "playback.view",
            "playback.control",
            "playback.volume",
            "devices.view",
            "schedules.view",
        ],
    },
    "VIEWER": {
        "name": "Viewer",
        "description": "Acceso de lectura a recursos autorizados.",
        "permissions": [
            "company.settings.view",
            "catalog.view",
            "playlists.view",
            "sites.view",
            "zones.view",
            "licenses.view",
            "channels.view",
            "playback.view",
            "schedules.view",
            "campaigns.view",
            "devices.view",
            "audit.view",
        ],
    },
}

OWNER_COMPANY_ROLE_CODE = "OWNER"
OFFICIAL_COMPANY_ROLE_CODES = tuple(COMPANY_ROLE_DEFINITIONS.keys())
