# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0003_initial'),
        ('organizations', '0002_initial'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='incident',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='devices.device'),
        ),
        migrations.AddField(
            model_name='incident',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='organizations.site'),
        ),
        migrations.AddField(
            model_name='incident',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='organizations.zone'),
        ),
        migrations.AddField(
            model_name='incidentevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentevent',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='support.incident'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='notification',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='support.incident'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['company', 'status'], name='support_inc_company_00e9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['created_at'], name='support_inc_created_e14bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['updated_at'], name='support_inc_updated_20a8cc_idx'),
        ),
    ]
