# Generated by Django 5.0.14 on 2026-07-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('playlists', '0002_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scheduling.schedule'),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='organizations.resourcescope'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_blocks', to='playlists.channel'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_blocks', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='scheduling.schedule'),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_exceptions', to='playlists.channel'),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_exceptions', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='scheduling.schedule'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['company', 'status'], name='scheduling__company_86a03f_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['created_at'], name='scheduling__created_49e54f_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['updated_at'], name='scheduling__updated_446f79_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleassignment',
            index=models.Index(fields=['company', 'is_active', 'priority'], name='scheduling__company_31eff1_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleassignment',
            index=models.Index(fields=['scope', 'is_active'], name='scheduling__scope_i_b2f230_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleassignment',
            index=models.Index(fields=['created_at'], name='scheduling__created_e2f6da_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleassignment',
            index=models.Index(fields=['updated_at'], name='scheduling__updated_a09a83_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleblock',
            index=models.Index(fields=['schedule', 'day_of_week', 'start_time'], name='scheduling__schedul_495a93_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleblock',
            index=models.Index(fields=['created_at'], name='scheduling__created_a14c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleblock',
            index=models.Index(fields=['updated_at'], name='scheduling__updated_12a99a_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduleblock',
            constraint=models.CheckConstraint(check=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='schedule_block_day_range'),
        ),
        migrations.AddConstraint(
            model_name='scheduleblock',
            constraint=models.CheckConstraint(check=models.Q(('volume_override__isnull', True), models.Q(('volume_override__gte', 0), ('volume_override__lte', 100)), _connector='OR'), name='schedule_block_volume_range'),
        ),
        migrations.AddConstraint(
            model_name='scheduleblock',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('channel__isnull', False), ('content_type', 'CHANNEL'), ('playlist__isnull', True)), models.Q(('channel__isnull', True), ('content_type', 'PLAYLIST'), ('playlist__isnull', False)), models.Q(('channel__isnull', True), ('content_type', 'SILENCE'), ('playlist__isnull', True)), _connector='OR'), name='schedule_block_content_target'),
        ),
    ]
