# Generated by Django 5.0.14 on 2026-08-02 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('VERIFY_EMAIL', 'Verify email'), ('RESET_PASSWORD', 'Reset password')], db_index=True, max_length=30)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verified_at'], name='users_email_v_00f951_idx'),
        ),
        migrations.AddField(
            model_name='useractiontoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='useractiontoken',
            index=models.Index(fields=['user', 'purpose', 'expires_at'], name='users_usera_user_id_9ab26d_idx'),
        ),
        migrations.AddIndex(
            model_name='useractiontoken',
            index=models.Index(fields=['purpose', 'expires_at'], name='users_usera_purpose_1fff90_idx'),
        ),
        migrations.AddIndex(
            model_name='useractiontoken',
            index=models.Index(fields=['created_at'], name='users_usera_created_1e1a79_idx'),
        ),
        migrations.AddConstraint(
            model_name='useractiontoken',
            constraint=models.UniqueConstraint(condition=models.Q(('consumed_at__isnull', True), ('revoked_at__isnull', True)), fields=('user', 'purpose'), name='uniq_active_user_action_token_purpose'),
        ),
    ]
